INCLUDEPATH += $$PWD

SOURCES += \
    $$PWD/lvgl/src/lv_core/lv_disp.c \
    $$PWD/lvgl/src/lv_core/lv_group.c \
    $$PWD/lvgl/src/lv_core/lv_indev.c \
    $$PWD/lvgl/src/lv_core/lv_obj.c \
    $$PWD/lvgl/src/lv_core/lv_refr.c \
    $$PWD/lvgl/src/lv_core/lv_style.c \
    $$PWD/lvgl/src/lv_draw/lv_draw_arc.c \
    $$PWD/lvgl/src/lv_draw/lv_draw_blend.c \
    $$PWD/lvgl/src/lv_draw/lv_draw_img.c \
    $$PWD/lvgl/src/lv_draw/lv_draw_label.c \
    $$PWD/lvgl/src/lv_draw/lv_draw_line.c \
    $$PWD/lvgl/src/lv_draw/lv_draw_mask.c \
    $$PWD/lvgl/src/lv_draw/lv_draw_rect.c \
    $$PWD/lvgl/src/lv_draw/lv_draw_triangle.c \
    $$PWD/lvgl/src/lv_draw/lv_img_buf.c \
    $$PWD/lvgl/src/lv_draw/lv_img_cache.c \
    $$PWD/lvgl/src/lv_draw/lv_img_decoder.c \
    $$PWD/lvgl/src/lv_font/lv_font.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_100.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_12.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_120.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_14.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_16.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_18.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_20.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_22.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_24.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_28.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_30.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_32.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_34.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_36.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_46.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_60.c \
    $$PWD/lvgl/src/lv_font/lv_font_123abc_80.c \
    $$PWD/lvgl/src/lv_font/lv_font_chinese_12.c \
    $$PWD/lvgl/src/lv_font/lv_font_chinese_14.c \
    $$PWD/lvgl/src/lv_font/lv_font_chinese_18.c \
    $$PWD/lvgl/src/lv_font/lv_font_chinese_20.c \
    $$PWD/lvgl/src/lv_font/lv_font_chinese_22.c \
    $$PWD/lvgl/src/lv_font/lv_font_chinese_24.c \
    $$PWD/lvgl/src/lv_font/lv_font_chinese_26.c \
    $$PWD/lvgl/src/lv_font/lv_font_chinese_28.c \
    $$PWD/lvgl/src/lv_font/lv_font_chinese_30.c \
    $$PWD/lvgl/src/lv_font/lv_font_chinese_32.c \
    $$PWD/lvgl/src/lv_font/lv_font_chinese_34.c \
    $$PWD/lvgl/src/lv_font/lv_font_chinese_36.c \
    $$PWD/lvgl/src/lv_font/lv_font_chinese_38.c \
    $$PWD/lvgl/src/lv_font/lv_font_dejavu_16_persian_hebrew.c \
    $$PWD/lvgl/src/lv_font/lv_font_fmt_txt.c \
    $$PWD/lvgl/src/lv_font/lv_font_loader.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_10.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_12.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_12_subpx.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_14.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_16.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_18.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_20.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_22.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_24.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_26.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_28.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_28_compressed.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_30.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_32.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_34.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_36.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_38.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_40.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_42.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_44.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_46.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_48.c \
    $$PWD/lvgl/src/lv_font/lv_font_montserrat_8.c \
    $$PWD/lvgl/src/lv_font/lv_font_roboto_12.c \
    $$PWD/lvgl/src/lv_font/lv_font_roboto_12_subpx.c \
    $$PWD/lvgl/src/lv_font/lv_font_roboto_16.c \
    $$PWD/lvgl/src/lv_font/lv_font_roboto_22.c \
    $$PWD/lvgl/src/lv_font/lv_font_roboto_28.c \
    $$PWD/lvgl/src/lv_font/lv_font_roboto_28_compressed.c \
    $$PWD/lvgl/src/lv_font/lv_font_simsun_16_cjk.c \
    $$PWD/lvgl/src/lv_font/lv_font_unscii_16.c \
    $$PWD/lvgl/src/lv_font/lv_font_unscii_8.c \
    $$PWD/lvgl/src/lv_font/lv_font_chinese_16.c \
    $$PWD/lvgl/src/lv_gpu/lv_gpu_nxp_pxp.c \
    $$PWD/lvgl/src/lv_gpu/lv_gpu_nxp_pxp_osa.c \
    $$PWD/lvgl/src/lv_gpu/lv_gpu_nxp_vglite.c \
    $$PWD/lvgl/src/lv_gpu/lv_gpu_stm32_dma2d.c \
    $$PWD/lvgl/src/lv_hal/lv_hal_disp.c \
    $$PWD/lvgl/src/lv_hal/lv_hal_indev.c \
    $$PWD/lvgl/src/lv_hal/lv_hal_tick.c \
    $$PWD/lvgl/src/lv_misc/lv_anim.c \
    $$PWD/lvgl/src/lv_misc/lv_area.c \
    $$PWD/lvgl/src/lv_misc/lv_async.c \
    $$PWD/lvgl/src/lv_misc/lv_bidi.c \
    $$PWD/lvgl/src/lv_misc/lv_color.c \
    $$PWD/lvgl/src/lv_misc/lv_debug.c \
    $$PWD/lvgl/src/lv_misc/lv_fs.c \
    $$PWD/lvgl/src/lv_misc/lv_gc.c \
    $$PWD/lvgl/src/lv_misc/lv_ll.c \
    $$PWD/lvgl/src/lv_misc/lv_log.c \
    $$PWD/lvgl/src/lv_misc/lv_math.c \
    $$PWD/lvgl/src/lv_misc/lv_mem.c \
    $$PWD/lvgl/src/lv_misc/lv_printf.c \
    $$PWD/lvgl/src/lv_misc/lv_task.c \
    $$PWD/lvgl/src/lv_misc/lv_templ.c \
    $$PWD/lvgl/src/lv_misc/lv_txt.c \
    $$PWD/lvgl/src/lv_misc/lv_txt_ap.c \
    $$PWD/lvgl/src/lv_misc/lv_utils.c \
    $$PWD/lvgl/src/lv_themes/lv_theme.c \
    $$PWD/lvgl/src/lv_themes/lv_theme_empty.c \
    $$PWD/lvgl/src/lv_themes/lv_theme_material.c \
    $$PWD/lvgl/src/lv_themes/lv_theme_mono.c \
    $$PWD/lvgl/src/lv_themes/lv_theme_template.c \
    $$PWD/lvgl/src/lv_widgets/lv_arc.c \
    $$PWD/lvgl/src/lv_widgets/lv_bar.c \
    $$PWD/lvgl/src/lv_widgets/lv_btn.c \
    $$PWD/lvgl/src/lv_widgets/lv_btnmatrix.c \
    $$PWD/lvgl/src/lv_widgets/lv_calendar.c \
    $$PWD/lvgl/src/lv_widgets/lv_canvas.c \
    $$PWD/lvgl/src/lv_widgets/lv_chart.c \
    $$PWD/lvgl/src/lv_widgets/lv_checkbox.c \
    $$PWD/lvgl/src/lv_widgets/lv_cont.c \
    $$PWD/lvgl/src/lv_widgets/lv_cpicker.c \
    $$PWD/lvgl/src/lv_widgets/lv_dropdown.c \
    $$PWD/lvgl/src/lv_widgets/lv_gauge.c \
    $$PWD/lvgl/src/lv_widgets/lv_img.c \
    $$PWD/lvgl/src/lv_widgets/lv_imgbtn.c \
    $$PWD/lvgl/src/lv_widgets/lv_keyboard.c \
    $$PWD/lvgl/src/lv_widgets/lv_label.c \
    $$PWD/lvgl/src/lv_widgets/lv_led.c \
    $$PWD/lvgl/src/lv_widgets/lv_line.c \
    $$PWD/lvgl/src/lv_widgets/lv_linemeter.c \
    $$PWD/lvgl/src/lv_widgets/lv_list.c \
    $$PWD/lvgl/src/lv_widgets/lv_msgbox.c \
    $$PWD/lvgl/src/lv_widgets/lv_objmask.c \
    $$PWD/lvgl/src/lv_widgets/lv_objx_templ.c \
    $$PWD/lvgl/src/lv_widgets/lv_page.c \
    $$PWD/lvgl/src/lv_widgets/lv_roller.c \
    $$PWD/lvgl/src/lv_widgets/lv_slider.c \
    $$PWD/lvgl/src/lv_widgets/lv_spinbox.c \
    $$PWD/lvgl/src/lv_widgets/lv_spinner.c \
    $$PWD/lvgl/src/lv_widgets/lv_switch.c \
    $$PWD/lvgl/src/lv_widgets/lv_table.c \
    $$PWD/lvgl/src/lv_widgets/lv_tabview.c \
    $$PWD/lvgl/src/lv_widgets/lv_textarea.c \
    $$PWD/lvgl/src/lv_widgets/lv_tileview.c \
    $$PWD/lvgl/src/lv_widgets/lv_win.c

HEADERS += \
    $$PWD/lv_conf.h \
    $$PWD/lvgl/lvgl.h \
    $$PWD/lvgl/src/lv_api_map.h \
    $$PWD/lvgl/src/lv_conf_internal.h \
    $$PWD/lvgl/src/lv_conf_kconfig.h \
    $$PWD/lvgl/src/lv_core/lv_disp.h \
    $$PWD/lvgl/src/lv_core/lv_group.h \
    $$PWD/lvgl/src/lv_core/lv_indev.h \
    $$PWD/lvgl/src/lv_core/lv_obj.h \
    $$PWD/lvgl/src/lv_core/lv_obj_style_dec.h \
    $$PWD/lvgl/src/lv_core/lv_refr.h \
    $$PWD/lvgl/src/lv_core/lv_style.h \
    $$PWD/lvgl/src/lv_draw/lv_draw.h \
    $$PWD/lvgl/src/lv_draw/lv_draw_arc.h \
    $$PWD/lvgl/src/lv_draw/lv_draw_blend.h \
    $$PWD/lvgl/src/lv_draw/lv_draw_img.h \
    $$PWD/lvgl/src/lv_draw/lv_draw_label.h \
    $$PWD/lvgl/src/lv_draw/lv_draw_line.h \
    $$PWD/lvgl/src/lv_draw/lv_draw_mask.h \
    $$PWD/lvgl/src/lv_draw/lv_draw_rect.h \
    $$PWD/lvgl/src/lv_draw/lv_draw_triangle.h \
    $$PWD/lvgl/src/lv_draw/lv_img_buf.h \
    $$PWD/lvgl/src/lv_draw/lv_img_cache.h \
    $$PWD/lvgl/src/lv_draw/lv_img_decoder.h \
    $$PWD/lvgl/src/lv_font/lv_font.h \
    $$PWD/lvgl/src/lv_font/lv_font_fmt_txt.h \
    $$PWD/lvgl/src/lv_font/lv_font_loader.h \
    $$PWD/lvgl/src/lv_font/lv_symbol_def.h \
    $$PWD/lvgl/src/lv_gpu/lv_gpu_nxp_pxp.h \
    $$PWD/lvgl/src/lv_gpu/lv_gpu_nxp_pxp_osa.h \
    $$PWD/lvgl/src/lv_gpu/lv_gpu_nxp_vglite.h \
    $$PWD/lvgl/src/lv_gpu/lv_gpu_stm32_dma2d.h \
    $$PWD/lvgl/src/lv_hal/lv_hal.h \
    $$PWD/lvgl/src/lv_hal/lv_hal_disp.h \
    $$PWD/lvgl/src/lv_hal/lv_hal_indev.h \
    $$PWD/lvgl/src/lv_hal/lv_hal_tick.h \
    $$PWD/lvgl/src/lv_misc/lv_anim.h \
    $$PWD/lvgl/src/lv_misc/lv_area.h \
    $$PWD/lvgl/src/lv_misc/lv_async.h \
    $$PWD/lvgl/src/lv_misc/lv_bidi.h \
    $$PWD/lvgl/src/lv_misc/lv_color.h \
    $$PWD/lvgl/src/lv_misc/lv_debug.h \
    $$PWD/lvgl/src/lv_misc/lv_fs.h \
    $$PWD/lvgl/src/lv_misc/lv_gc.h \
    $$PWD/lvgl/src/lv_misc/lv_ll.h \
    $$PWD/lvgl/src/lv_misc/lv_log.h \
    $$PWD/lvgl/src/lv_misc/lv_math.h \
    $$PWD/lvgl/src/lv_misc/lv_mem.h \
    $$PWD/lvgl/src/lv_misc/lv_printf.h \
    $$PWD/lvgl/src/lv_misc/lv_task.h \
    $$PWD/lvgl/src/lv_misc/lv_templ.h \
    $$PWD/lvgl/src/lv_misc/lv_txt.h \
    $$PWD/lvgl/src/lv_misc/lv_txt_ap.h \
    $$PWD/lvgl/src/lv_misc/lv_types.h \
    $$PWD/lvgl/src/lv_misc/lv_utils.h \
    $$PWD/lvgl/src/lv_themes/lv_theme.h \
    $$PWD/lvgl/src/lv_themes/lv_theme_empty.h \
    $$PWD/lvgl/src/lv_themes/lv_theme_material.h \
    $$PWD/lvgl/src/lv_themes/lv_theme_mono.h \
    $$PWD/lvgl/src/lv_themes/lv_theme_template.h \
    $$PWD/lvgl/src/lv_widgets/lv_arc.h \
    $$PWD/lvgl/src/lv_widgets/lv_bar.h \
    $$PWD/lvgl/src/lv_widgets/lv_btn.h \
    $$PWD/lvgl/src/lv_widgets/lv_btnmatrix.h \
    $$PWD/lvgl/src/lv_widgets/lv_calendar.h \
    $$PWD/lvgl/src/lv_widgets/lv_canvas.h \
    $$PWD/lvgl/src/lv_widgets/lv_chart.h \
    $$PWD/lvgl/src/lv_widgets/lv_checkbox.h \
    $$PWD/lvgl/src/lv_widgets/lv_cont.h \
    $$PWD/lvgl/src/lv_widgets/lv_cpicker.h \
    $$PWD/lvgl/src/lv_widgets/lv_dropdown.h \
    $$PWD/lvgl/src/lv_widgets/lv_gauge.h \
    $$PWD/lvgl/src/lv_widgets/lv_img.h \
    $$PWD/lvgl/src/lv_widgets/lv_imgbtn.h \
    $$PWD/lvgl/src/lv_widgets/lv_keyboard.h \
    $$PWD/lvgl/src/lv_widgets/lv_label.h \
    $$PWD/lvgl/src/lv_widgets/lv_led.h \
    $$PWD/lvgl/src/lv_widgets/lv_line.h \
    $$PWD/lvgl/src/lv_widgets/lv_linemeter.h \
    $$PWD/lvgl/src/lv_widgets/lv_list.h \
    $$PWD/lvgl/src/lv_widgets/lv_msgbox.h \
    $$PWD/lvgl/src/lv_widgets/lv_objmask.h \
    $$PWD/lvgl/src/lv_widgets/lv_objx_templ.h \
    $$PWD/lvgl/src/lv_widgets/lv_page.h \
    $$PWD/lvgl/src/lv_widgets/lv_roller.h \
    $$PWD/lvgl/src/lv_widgets/lv_slider.h \
    $$PWD/lvgl/src/lv_widgets/lv_spinbox.h \
    $$PWD/lvgl/src/lv_widgets/lv_spinner.h \
    $$PWD/lvgl/src/lv_widgets/lv_switch.h \
    $$PWD/lvgl/src/lv_widgets/lv_table.h \
    $$PWD/lvgl/src/lv_widgets/lv_tabview.h \
    $$PWD/lvgl/src/lv_widgets/lv_textarea.h \
    $$PWD/lvgl/src/lv_widgets/lv_tileview.h \
    $$PWD/lvgl/src/lv_widgets/lv_win.h \
